# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'spec/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/*'
  TargetRubyVersion: 2.2
  DisplayCopNames: true

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/ParallelAssignment:
  Enabled: false

Metrics/LineLength:
  Max: 155

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ModuleLength:
  Max: 120

Style/MutableConstant:
  Enabled: false

Style/Alias:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/RedundantSelf:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
