:verbose: false
:pidfile: ./tmp/pids/sidekiq.pids
:logfile: ./log/sidekiq.log
:concurrency: 10
:queues:
  - notifications
  - default

development:
  :namespace: rubyboost_development

production:
  :namespace: rubyboost_production
